=== slepher/x4-station-calculator/x4raw_assets/9.0-Empire-beta/libraries/regionyields/regionyields.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="regionyields">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="definition" minOccurs="0" maxOccurs="unbounded">
          <xs:annotation>
            <xs:documentation>
              A region object group, to be referenced in region_definitions.xml
            </xs:documentation>
          </xs:annotation>
          <xs:complexType>
            <xs:sequence>
              <xs:element name="boundary">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="position" minOccurs="0" maxOccurs="1">
                      <xs:annotation>
                        <xs:documentation>
                          Boundary position offset
                        </xs:documentation>
                      </xs:annotation>
                      <xs:complexType>
                        <xs:attribute name="x" type="xs:float" />
                        <xs:attribute name="y" type="xs:float" />
                        <xs:attribute name="z" type="xs:float" />
                      </xs:complexType>
                    </xs:element>
                    <xs:choice minOccurs="0" maxOccurs="1">
                      <xs:element name="rotation">
                        <xs:annotation>
                          <xs:documentation>
                            Boundary rotation offset
                          </xs:documentation>
                        </xs:annotation>
                        <xs:complexType>
                          <xs:attribute name="yaw" type="xs:float" />
                          <xs:attribute name="pitch" type="xs:float" />
                          <xs:attribute name="roll" type="xs:float" />
                        </xs:complexType>
                      </xs:element>
                      <xs:element name="quaternion">
                        <xs:annotation>
                          <xs:documentation>
                            Boundary rotation offset
                          </xs:documentation>
                        </xs:annotation>
                        <xs:complexType>
                          <xs:attribute name="qw" type="xs:float" />
                          <xs:attribute name="qx" type="xs:float" />
                          <xs:attribute name="qy" type="xs:float" />
                          <xs:attribute name="qz" type="xs:float" />
                        </xs:complexType>
                      </xs:element>
                    </xs:choice>
                    <xs:element minOccurs="1" maxOccurs="1" name="size">
                      <xs:complexType>
                        <xs:attribute name="r">
                          <xs:annotation>
                            <xs:documentation>
                              Radius for sphere, cylinder or spline tube boundaries.
                            </xs:documentation>
                          </xs:annotation>
                          <xs:simpleType>
                            <xs:restriction base="xs:float">
                              <xs:minExclusive value="0" />
                            </xs:restriction>
                          </xs:simpleType>
                        </xs:attribute>
                        <xs:attribute name="linear">
                          <xs:annotation>
                            <xs:documentation>
                              Height for cylinder boundaries.
                            </xs:documentation>
                          </xs:annotation>
                          <xs:simpleType>
                            <xs:restriction base="xs:float">
                              <xs:minExclusive value="0" />
                            </xs:restriction>
                          </xs:simpleType>
                        </xs:attribute>
                        <xs:attribute name="x">
                          <xs:annotation>
                            <xs:documentation>
                              Side length in x direction for box boundaries.
                            </xs:documentation>
                          </xs:annotation>
                          <xs:simpleType>
                            <xs:restriction base="xs:float">
                              <xs:minExclusive value="0" />
                            </xs:restriction>
                          </xs:simpleType>
                        </xs:attribute>
                        <xs:attribute name="y">
                          <xs:annotation>
                            <xs:documentation>
                              Side length in y direction for box boundaries.
                            </xs:documentation>
                          </xs:annotation>
                          <xs:simpleType>
                            <xs:restriction base="xs:float">
                              <xs:minExclusive value="0" />
                            </xs:restriction>
                          </xs:simpleType>
                        </xs:attribute>
                        <xs:attribute name="z">
                          <xs:annotation>
                            <xs:documentation>
                              Side length in z direction for box boundaries.
                            </xs:documentation>
                          </xs:annotation>
                          <xs:simpleType>
                            <xs:restriction base="xs:float">
                              <xs:minExclusive value="0" />
                            </xs:restriction>
                          </xs:simpleType>
                        </xs:attribute>
                      </xs:complexType>
                    </xs:element>
                    <xs:element minOccurs="0" maxOccurs="unbounded" name="splineposition">
                      <xs:annotation>
                        <xs:documentation>
                          Spline point. Coordinates are relative to the region. tx/ty/tz are the tangent direction.
                        </xs:documentation>
                      </xs:annotation>
                      <xs:complexType>
                        <xs:attribute name="x" type="xs:float" />
                        <xs:attribute name="y" type="xs:float" />
                        <xs:attribute name="z" type="xs:float" />
                        <xs:attribute name="tx" type="xs:float" />
                        <xs:attribute name="ty" type="xs:float" />
                        <xs:attribute name="tz" type="xs:float" />
                        <xs:attribute name="inlength">
                          <xs:annotation>
                            <xs:documentation>
                              Incoming tangent length.
                            </xs:documentation>
                          </xs:annotation>
                          <xs:simpleType>
                            <xs:restriction base="xs:float">
                              <xs:minExclusive value="0" />
                            </xs:restriction>
                          </xs:simpleType>
                        </xs:attribute>
                        <xs:attribute name="outlength">
                          <xs:annotation>
                            <xs:documentation>
                              Outgoing tangent length.
                            </xs:documentation>
                          </xs:annotation>
                          <xs:simpleType>
                            <xs:restriction base="xs:float">
                              <xs:minExclusive value="0" />
                            </xs:restriction>
                          </xs:simpleType>
                        </xs:attribute>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                  <xs:attribute name="class" use="required">
                    <xs:simpleType>
                      <xs:restriction base="xs:NMTOKEN">
                        <xs:enumeration value="box" />
                        <xs:enumeration value="sphere" />
                        <xs:enumeration value="cylinder" />
                        <xs:enumeration value="splinetube" />
                      </xs:restriction>
                    </xs:simpleType>
                  </xs:attribute>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
            <xs:attribute name="id" type="xs:ID" use="required">
              <xs:annotation>
                <xs:documentation>
                  The ID of this region yield area definition
                </xs:documentation>
              </xs:annotation>
            </xs:attribute>
            <xs:attribute name="ware" use="required">
              <xs:annotation>
                <xs:documentation>
                  The ware ID of the contained resource
                </xs:documentation>
              </xs:annotation>
              <xs:simpleType>
                <xs:restriction base="xs:NMTOKEN">
                  <xs:enumeration value="ore" />
                  <xs:enumeration value="nividium" />
                  <xs:enumeration value="silicon" />
                  <xs:enumeration value="ice" />
                  <xs:enumeration value="hydrogen" />
                  <xs:enumeration value="helium" />
                  <xs:enumeration value="methane" />
                  <xs:enumeration value="rawscrap" />
                  <xs:enumeration value="rawkhaakscrap" />
                </xs:restriction>
              </xs:simpleType>
            </xs:attribute>
            <xs:attribute name="yield" type="xs:positiveInteger" use="required">
              <xs:annotation>
                <xs:documentation>
                  The total amount of yield in this area
                </xs:documentation>
              </xs:annotation>
            </xs:attribute>
            <xs:attribute name="objectyieldfactor">
              <xs:annotation>
                <xs:documentation>
                  An optional factor to the yield contained in each object (not relevant for liquid resources). Defaults to 1
                </xs:documentation>
              </xs:annotation>
              <xs:simpleType>
                <xs:restriction base="xs:float">
                  <xs:minExclusive value="0" />
                </xs:restriction>
              </xs:simpleType>
            </xs:attribute>
            <xs:attribute name="gatherspeedfactor" type="xs:float">
              <xs:annotation>
                <xs:documentation>
                  The gather speed factor (only relevant for liquid resources). Defaults to 1
                </xs:documentation>
              </xs:annotation>
            </xs:attribute>
            <xs:attribute name="respawndelay" type="xs:float">
              <xs:annotation>
                <xs:documentation>
                  The time after it was depleted (in minutes) before this resource area is respawned at a random location. Defaults to 0. Set to -1 to prevent respawning
                </xs:documentation>
              </xs:annotation>
            </xs:attribute>
            <xs:attribute name="rating" use="required">
              <xs:annotation>
                <xs:documentation>
                  The star rating of this resource area, multiplied by 3. Maximum value of 15 is 5 stars.
                </xs:documentation>
              </xs:annotation>
              <xs:simpleType>
                <xs:restriction base="xs:integer">
                  <xs:minInclusive value="0" />
                  <xs:maxInclusive value="15" />
                </xs:restriction>
              </xs:simpleType>
            </xs:attribute>
            <xs:attribute name="tag" type="xs:string">
              <xs:annotation>
                <xs:documentation>
                  An optional compatibility tag - needs to be set if it should appear in regions that have a yield tag list defined for this ware.
                </xs:documentation>
              </xs:annotation>
            </xs:attribute>
            <xs:attribute name="randompitch" type="xs:boolean">
              <xs:annotation>
                <xs:documentation>
                  Whether the pitch angle should be randomized on spawn
                </xs:documentation>
              </xs:annotation>
            </xs:attribute>
            <xs:attribute name="randomyaw" type="xs:boolean">
              <xs:annotation>
                <xs:documentation>
                  Whether the yaw angle should be randomized on spawn
                </xs:documentation>
              </xs:annotation>
            </xs:attribute>
            <xs:attribute name="randomroll" type="xs:boolean">
              <xs:annotation>
                <xs:documentation>
                  Whether the roll angle should be randomized on spawn
                </xs:documentation>
              </xs:annotation>
            </xs:attribute>
            <xs:attribute name="scaneffect" type="xs:string" use="optional">
              <xs:annotation>
                <xs:documentation>
                  The scan result effect definition, see libraries/effects.xml
                </xs:documentation>
              </xs:annotation>
            </xs:attribute>
            <xs:attribute name="scaneffectcolor" type="xs:string" use="optional">
              <xs:annotation>
                <xs:documentation>
                  The scan result effect color (from libraries/colors.xml), defaults to white if not set
                </xs:documentation>
              </xs:annotation>
            </xs:attribute>
            <xs:attribute name="scaneffectamount" type="xs:nonNegativeInteger" use="optional">
              <xs:annotation>
                <xs:documentation>
                  The scan result effect amount, defaults to 1
                </xs:documentation>
              </xs:annotation>
            </xs:attribute>
            <xs:attribute name="scaneffectintensity" type="xs:float">
              <xs:annotation>
                <xs:documentation>
                  The scan result effect intensity (opacity, volume, etc.), defaults to 1.0
                </xs:documentation>
              </xs:annotation>
            </xs:attribute>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== slepher/x4-station-calculator/x4raw_assets/8.0-Diplomacy/libraries/regionyields/final.xml
<?xml version='1.0' encoding='UTF-8'?>
<regionyields xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="regionyields.xsd">
  <resource ware="ore" effect_r="207" effect_g="127" effect_b="84">
    <yield name="lowest" resourcedensity="0.026" replenishtime="600" scaneffect="scfx_dynamic_lowyield_01" scaneffectdensity="0.01" scaneffectintensity="0.1"/>
    <yield name="verylow" resourcedensity="0.06" replenishtime="1200" scaneffect="scfx_dynamic_lowyield_01" scaneffectdensity="0.01" scaneffectintensity="0.3"/>
    <yield name="lowminus" resourcedensity="0.2" replenishtime="1200" scaneffect="scfx_dynamic_lowyield_01" scaneffectdensity="0.01" scaneffectintensity="0.3"/>
    <yield name="low" resourcedensity="0.6" replenishtime="1800" scaneffect="scfx_dynamic_lowyield_01" scaneffectdensity="0.01" scaneffectintensity="0.6"/>
    <yield name="lowplus" resourcedensity="1.8" replenishtime="1800" scaneffect="scfx_dynamic_lowyield_01" scaneffectdensity="0.01" scaneffectintensity="0.6"/>
    <yield name="lowextra" resourcedensity="3.2" replenishtime="1900" scaneffect="scfx_dynamic_lowyield_01" scaneffectdensity="0.01" scaneffectintensity="0.6"/>
    <yield name="medlow" resourcedensity="4" replenishtime="2000" scaneffect="scfx_dynamic_normalyield_01" scaneffectdensity="0.01" scaneffectintensity="1.0"/>
    <yield name="medium" resourcedensity="6" replenishtime="2400" scaneffect="scfx_dynamic_normalyield_01" scaneffectdensity="0.01" scaneffectintensity="1.0"/>
    <yield name="medplus" resourcedensity="16" replenishtime="2400" scaneffect="scfx_dynamic_normalyield_01" scaneffectdensity="0.01" scaneffectintensity="1.0"/>
    <yield name="medhigh" resourcedensity="32" replenishtime="2400" scaneffect="scfx_dynamic_normalyield_01" scaneffectdensity="0.01" scaneffectintensity="1.0"/>
    <yield name="highlow" resourcedensity="48" replenishtime="3600" scaneffect="scfx_dynamic_highyield_01" scaneffectdensity="0.01" scaneffectintensity="1.0"/>
    <yield name="high" resourcedensity="60" replenishtime="3600" scaneffect="scfx_dynamic_highyield_01" scaneffectdensity="0.01" scaneffectintensity="1.0"/>
    <yield name="highplus" resourcedensity="120" replenishtime="3600" scaneffect="scfx_dynamic_highyield_01" scaneffectdensity="0.01" scaneffectintensity="1.0"/>
    <yield name="veryhigh" resourcedensity="3600" replenishtime="18000" scaneffect="scfx_dynamic_highyield_01" scaneffectdensity="0.01" scaneffectintensity="1.0"/>
    <yield name="highest" resourcedensity="60000" replenishtime="24000" scaneffect="scfx_dynamic_highyield_01" scaneffectdensity="0.01" scaneffectintensity="1.0"/>
  </resource>
  <resource ware="silicon" effect_r="166" effect_g="166" effect_b="175">
    <yield name="lowest" resourcedensity="0.026" replenishtime="600" scaneffect="scfx_dynamic_lowyield_01" scaneffectdensity="0.01" scaneffectintensity="0.1"/>
    <yield name="verylow" resourcedensity="0.06" replenishtime="1200" scaneffect="scfx_dynamic_lowyield_01" scaneffectdensity="0.01" scaneffectintensity="0.3"/>
    <yield name="lowminus" resourcedensity="0.2" replenishtime="1200" scaneffect="scfx_dynamic_lowyield_01" scaneffectdensity="0.01" scaneffectintensity="0.3"/>
    <yield name="low" resourcedensity="0.6" replenishtime="1800" scaneffect="scfx_dynamic_lowyield_01" scaneffectdensity="0.01" scaneffectintensity="0.6"/>
    <yield name="lowplus" resourcedensity="1.8" replenishtime="1800" scaneffect="scfx_dynamic_lowyield_01" scaneffectdensity="0.01" scaneffectintensity="0.6"/>
    <yield name="lowextra" resourcedensity="3.2" replenishtime="1900" scaneffect="scfx_dynamic_lowyield_01" scaneffectdensity="0.01" scaneffectintensity="0.6"/>
    <yield name="medlow" resourcedensity="4" replenishtime="2000" scaneffect="scfx_dynamic_normalyield_01" scaneffectdensity="0.01" scaneffectintensity="1.0"/>
    <yield name="medium" resourcedensity="6" replenishtime="2400" scaneffect="scfx_dynamic_normalyield_01" scaneffectdensity="0.01" scaneffectintensity="1.0"/>
    <yield name="medplus" resourcedensity="16" replenishtime="2400" scaneffect="scfx_dynamic_normalyield_01" scaneffectdensity="0.01" scaneffectintensity="1.0"/>
    <yield name="medhigh" resourcedensity="32" replenishtime="2400" scaneffect="scfx_dynamic_normalyield_01" scaneffectdensity="0.01" scaneffectintensity="1.0"/>
    <yield name="highlow" resourcedensity="48" replenishtime="3600" scaneffect="scfx_dynamic_highyield_01" scaneffectdensity="0.01" scaneffectintensity="1.0"/>
    <yield name="high" resourcedensity="60" replenishtime="3600" scaneffect="scfx_dynamic_highyield_01" scaneffectdensity="0.01" scaneffectintensity="1.0"/>
    <yield name="highplus" resourcedensity="120" replenishtime="3600" scaneffect="scfx_dynamic_highyield_01" scaneffectdensity="0.01" scaneffectintensity="1.0"/>
    <yield name="veryhigh" resourcedensity="3600" replenishtime="18000" scaneffect="scfx_dynamic_highyield_01" scaneffectdensity="0.01" scaneffectintensity="1.0"/>
    <yield name="highest" resourcedensity="60000" replenishtime="24000" scaneffect="scfx_dynamic_highyield_01" scaneffectdensity="0.01" scaneffectintensity="1.0"/>
  </resource>
  <resource ware="ice" effect_r="208" effect_g="208" effect_b="215">
    <yield name="lowest" resourcedensity="0.015" replenishtime="180" scaneffect="scfx_dynamic_lowyield_01" scaneffectdensity="0.01" scaneffectintensity="0.3"/>
    <yield name="verylow" resourcedensity="0.15" replenishtime="180" scaneffect="scfx_dynamic_lowyield_01" scaneffectdensity="0.01" scaneffectintensity="0.3"/>
    <yield name="lowminus" resourcedensity="0.6" replenishtime="300" scaneffect="scfx_dynamic_lowyield_01" scaneffectdensity="0.01" scaneffectintensity="0.3"/>
    <yield name="low" resourcedensity="1.5" replenishtime="300" scaneffect="scfx_dynamic_lowyield_01" scaneffectdensity="0.01" scaneffectintensity="1.0"/>
    <yield name="lowplus" resourcedensity="4" replenishtime="600" scaneffect="scfx_dynamic_lowyield_01" scaneffectdensity="0.01" scaneffectintensity="1.0"/>
    <yield name="lowextra" resourcedensity="8" replenishtime="600" scaneffect="scfx_dynamic_lowyield_01" scaneffectdensity="0.01" scaneffectintensity="1.0"/>
    <yield name="medlow" resourcedensity="9" replenishtime="600" scaneffect="scfx_dynamic_normalyield_01" scaneffectdensity="0.01" scaneffectintensity="1.0"/>
    <yield name="medium" resourcedensity="15" replenishtime="600" scaneffect="scfx_dynamic_normalyield_01" scaneffectdensity="0.01" scaneffectintensity="1.0"/>
    <yield name="medplus" resourcedensity="30" replenishtime="2400" scaneffect="scfx_dynamic_normalyield_01" scaneffectdensity="0.01" scaneffectintensity="1.0"/>
    <yield name="medhigh" resourcedensity="60" replenishtime="600" scaneffect="scfx_dynamic_normalyield_01" scaneffectdensity="0.01" scaneffectintensity="1.0"/>
    <yield name="highlow" resourcedensity="90" replenishtime="3600" scaneffect="scfx_dynamic_highyield_01" scaneffectdensity="0.01" scaneffectintensity="1.0"/>
    <yield name="high" resourcedensity="150" replenishtime="1200" scaneffect="scfx_dynamic_highyield_01" scaneffectdensity="0.01" scaneffectintensity="1.0"/>
    <yield name="highplus" resourcedensity="600" replenishtime="3600" scaneffect="scfx_dynamic_highyield_01" scaneffectdensity="0.01" scaneffectintensity="1.0"/>
    <yield name="veryhigh" resourcedensity="1500" replenishtime="2400" scaneffect="scfx_dynamic_highyield_01" scaneffectdensity="0.01" scaneffectintensity="1.0"/>
    <yield name="highest" resourcedensity="30000" replenishtime="18000" scaneffect="scfx_dynamic_highyield_01" scaneffectdensity="0.01" scaneffectintensity="1.0"/>
  </resource>
  <resource ware="nividium" effect_r="230" effect_g="150" effect_b="230">
    <yield name="lowest" resourcedensity="0.00001" replenishtime="2400" scaneffect="scfx_dynamic_lowyield_01" scaneffectdensity="0.01" scaneffectintensity="1.0"/>
    <yield name="verylow" resourcedensity="0.00003" replenishtime="3600" scaneffect="scfx_dynamic_lowyield_01" scaneffectdensity="0.01" scaneffectintensity="1.0"/>
    <yield name="lowminus" resourcedensity="0.00005" replenishtime="4800" scaneffect="scfx_dynamic_lowyield_01" scaneffectdensity="0.01" scaneffectintensity="1.0"/>
    <yield name="low" resourcedensity="0.0001" replenishtime="5040" scaneffect="scfx_dynamic_lowyield_01" scaneffectdensity="0.01" scaneffectintensity="1.0"/>
    <yield name="lowplus" resourcedensity="0.0002" replenishtime="6400" scaneffect="scfx_dynamic_lowyield_01" scaneffectdensity="0.01" scaneffectintensity="1.0"/>
    <yield name="lowextra" resourcedensity="0.0004" replenishtime="7000" scaneffect="scfx_dynamic_lowyield_01" scaneffectdensity="0.01" scaneffectintensity="1.0"/>
    <yield name="medlow" resourcedensity="0.0006" replenishtime="7200" scaneffect="scfx_dynamic_normalyield_01" scaneffectdensity="0.01" scaneffectintensity="1.0"/>
    <yield name="medium" resourcedensity="0.001" replenishtime="10080" scaneffect="scfx_dynamic_normalyield_01" scaneffectdensity="0.01" scaneffectintensity="1.0"/>
    <yield name="medplus" resourcedensity="0.002" replenishtime="12440" scaneffect="scfx_dynamic_normalyield_01" scaneffectdensity="0.01" scaneffectintensity="1.0"/>
    <yield name="medhigh" resourcedensity="0.004" replenishtime="14400" scaneffect="scfx_dynamic_normalyield_01" scaneffectdensity="0.01" scaneffectintensity="1.0"/>
    <yield name="highlow" resourcedensity="0.008" replenishtime="16800" scaneffect="scfx_dynamic_highyield_01" scaneffectdensity="0.01" scaneffectintensity="1.0"/>
    <yield name="high" resourcedensity="0.01" replenishtime="20160" scaneffect="scfx_dynamic_highyield_01" scaneffectdensity="0.01" scaneffectintensity="1.0"/>
    <yield name="highplus" resourcedensity="0.04" replenishtime="32000" scaneffect="scfx_dynamic_highyield_01" scaneffectdensity="0.01" scaneffectintensity="1.0"/>
    <yield name="veryhigh" resourcedensity="0.1" replenishtime="40320" scaneffect="scfx_dynamic_highyield_01" scaneffectdensity="0.01" scaneffectintensity="1.0"/>
