=== slepher/x4-station-calculator/x4raw_assets/9.0-Empire/libraries/regionobjectgroups/regionobjectgroups.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="groups">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="group" minOccurs="0" maxOccurs="unbounded">
          <xs:annotation>
            <xs:documentation>
              A region object group, to be referenced in region_definitions.xml
            </xs:documentation>
          </xs:annotation>
          <xs:complexType>
            <xs:sequence>
              <xs:element name="select" minOccurs="0" maxOccurs="unbounded">
                <xs:complexType>
                  <xs:attribute name="macro" use="required">
                    <xs:annotation>
                      <xs:documentation>
                        The macro name of the region object
                      </xs:documentation>
                    </xs:annotation>
                  </xs:attribute>
                  <xs:attribute name="weight">
                    <xs:annotation>
                      <xs:documentation>
                        The weight of this macro selection (defaults to 1)
                      </xs:documentation>
                    </xs:annotation>
                  </xs:attribute>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
            <xs:attribute name="name" use="required" type="xs:ID">
              <xs:annotation>
                <xs:documentation>
                  The name of this region object group
                </xs:documentation>
              </xs:annotation>
            </xs:attribute>
            <xs:attribute name="resource">
              <xs:annotation>
                <xs:documentation>
                  The resource ware ID to be assigned when this group is used
                </xs:documentation>
              </xs:annotation>
              <xs:simpleType>
                <xs:restriction base="xs:NMTOKEN">
                  <xs:enumeration value="ore" />
                  <xs:enumeration value="nividium" />
                  <xs:enumeration value="silicon" />
                  <xs:enumeration value="ice" />
                  <xs:enumeration value="hydrogen" />
                  <xs:enumeration value="helium" />
                  <xs:enumeration value="methane" />
                  <xs:enumeration value="rawscrap" />
                  <xs:enumeration value="rawkhaakscrap" />
                </xs:restriction>
              </xs:simpleType>
            </xs:attribute>
            <xs:attribute name="yield">
              <xs:annotation>
                <xs:documentation>
                  The base yield for region objects in this group
                </xs:documentation>
              </xs:annotation>
            </xs:attribute>
            <xs:attribute name="yieldvariation">
              <xs:annotation>
                <xs:documentation>
                  The yield variation fraction for region objects in this group, as a fraction of the base yield. Must be between 0 and 1. Defaults to 0.
                </xs:documentation>
              </xs:annotation>
              <xs:simpleType>
                <xs:restriction base="xs:float">
                  <xs:minInclusive value="0" />
                  <xs:maxInclusive value="1" />
                </xs:restriction>
              </xs:simpleType>
            </xs:attribute>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== slepher/x4-station-calculator/x4raw_assets/8.0-Diplomacy/libraries/regionobjectgroups/final.xml
<?xml version='1.0' encoding='UTF-8'?>
<groups xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="regionobjectgroups.xsd">
  <!--Asteroid groups (regular ones with resources)-->
  <group name="asteroid_highyield_v1" resource="ore" yield="2400" yieldvariation="0.5">
    <select macro="env_ast_niv_l_01_macro"/>
    <select macro="env_ast_niv_l_02_macro"/>
    <!--select macro="rock_test_macro" />
    <select macro="rock_test_noise_macro" /-->
    <!--select macro="asteroid_highyield_ore_v1_macro" /-->
    <select macro="env_ast_ore_l_01_macro"/>
    <select macro="env_ast_ore_l_02_macro"/>
    <select macro="env_ast_ore_l_03_macro"/>
  </group>
  <group name="asteroid_highyield_sil_v1" resource="silicon" yield="2400" yieldvariation="0.5">
    <select macro="env_ast_niv_l_01_macro"/>
    <select macro="env_ast_niv_l_02_macro"/>
    <!--select macro="rock_test_macro" />
    <select macro="rock_test_noise_macro" /-->
    <!--select macro="asteroid_highyield_ore_v1_macro" /-->
    <select macro="env_ast_crystal_l_01_macro"/>
    <select macro="env_ast_crystal_l_02_macro"/>
    <select macro="env_ast_crystal_l_03_macro"/>
  </group>
  <group name="asteroid_highyield_niv_v1" resource="nividium" yield="2400" yieldvariation="0.5">
    <select macro="env_ast_niv_l_01_macro"/>
    <select macro="env_ast_niv_l_02_macro"/>
    <select macro="env_ast_niv_l_03_macro"/>
    <select macro="env_ast_niv_l_04_macro"/>
    <select macro="env_ast_niv_l_05_macro"/>
  </group>
  <group name="asteroid_ore_xxl" resource="ore" yield="800" yieldvariation="0.5">
    <select macro="env_ast_ore_xxl_01_macro"/>
  </group>
  <group name="asteroid_ore_xl" resource="ore" yield="800" yieldvariation="0.5">
    <select macro="env_ast_ore_xl_01_macro"/>
    <select macro="env_ast_ore_xl_02_macro"/>
  </group>
  <group name="asteroid_ore_l" resource="ore" yield="400" yieldvariation="0.5">
    <select macro="env_ast_ore_l_01_macro"/>
    <select macro="env_ast_ore_l_02_macro"/>
    <select macro="env_ast_ore_l_03_macro"/>
    <select macro="env_ast_ore_l_04_macro"/>
    <select macro="env_ast_ore_l_05_macro"/>
  </group>
  <group name="asteroid_ore_m" resource="ore" yield="200" yieldvariation="0.5">
    <select macro="env_ast_ore_m_01_macro"/>
    <select macro="env_ast_ore_m_02_macro"/>
    <select macro="env_ast_ore_m_03_macro"/>
    <select macro="env_ast_ore_m_04_macro"/>
    <select macro="env_ast_ore_m_05_macro"/>
    <select macro="env_ast_ore_m_06_macro"/>
  </group>
  <group name="asteroid_ore_s" resource="ore" yield="100" yieldvariation="0.5">
    <select macro="env_ast_ore_s_01_macro"/>
    <select macro="env_ast_ore_s_02_macro"/>
    <select macro="env_ast_ore_s_03_macro"/>
    <select macro="env_ast_ore_s_04_macro"/>
    <select macro="env_ast_ore_s_05_macro"/>
  </group>
  <group name="asteroid_ore_xs" resource="ore" yield="10" yieldvariation="0.5">
    <select macro="env_ast_ore_xs_01_macro"/>
    <select macro="env_ast_ore_xs_02_macro"/>
    <select macro="env_ast_ore_xs_03_macro"/>
    <select macro="env_ast_ore_xs_04_macro"/>
    <select macro="env_ast_ore_xs_05_macro"/>
  </group>
  <group name="asteroid_silicon_xl" resource="silicon" yield="800" yieldvariation="0.5">
    <select macro="env_ast_crystal_xl_01_macro"/>
  </group>
  <group name="asteroid_silicon_l" resource="silicon" yield="400" yieldvariation="0.5">
    <select macro="env_ast_crystal_l_01_macro"/>
    <select macro="env_ast_crystal_l_02_macro"/>
    <select macro="env_ast_crystal_l_03_macro"/>
  </group>
  <group name="asteroid_silicon_m" resource="silicon" yield="200" yieldvariation="0.5">
    <select macro="env_ast_crystal_m_01_macro"/>
    <select macro="env_ast_crystal_m_02_macro"/>
    <select macro="env_ast_crystal_m_03_macro"/>
    <select macro="env_ast_crystal_m_04_macro"/>
    <select macro="env_ast_crystal_m_05_macro"/>
    <select macro="env_ast_crystal_m_06_macro"/>
  </group>
  <group name="asteroid_silicon_s" resource="silicon" yield="100" yieldvariation="0.5">
    <select macro="env_ast_crystal_s_01_macro"/>
    <select macro="env_ast_crystal_s_02_macro"/>
    <select macro="env_ast_crystal_s_03_macro"/>
    <select macro="env_ast_crystal_s_04_macro"/>
    <select macro="env_ast_crystal_s_05_macro"/>
    <select macro="env_ast_crystal_s_06_macro"/>
  </group>
  <group name="asteroid_silicon_xs" resource="silicon" yield="10" yieldvariation="0.5">
    <select macro="env_ast_crystal_xs_01_macro"/>
    <select macro="env_ast_crystal_xs_02_macro"/>
    <select macro="env_ast_crystal_xs_03_macro"/>
    <select macro="env_ast_crystal_xs_04_macro"/>
    <select macro="env_ast_crystal_xs_05_macro"/>
    <select macro="env_ast_crystal_xs_06_macro"/>
  </group>
  <group name="asteroid_nividium_l" resource="nividium" yield="400" yieldvariation="0.5">
    <select macro="env_ast_niv_l_01_macro"/>
    <select macro="env_ast_niv_l_02_macro"/>
    <select macro="env_ast_niv_l_03_macro"/>
    <select macro="env_ast_niv_l_04_macro"/>
    <select macro="env_ast_niv_l_05_macro"/>
  </group>
  <group name="asteroid_nividium_m" resource="nividium" yield="200" yieldvariation="0.5">
    <select macro="env_ast_niv_m_01_macro"/>
    <select macro="env_ast_niv_m_02_macro"/>
    <select macro="env_ast_niv_m_03_macro"/>
    <select macro="env_ast_niv_m_04_macro"/>
    <select macro="env_ast_niv_m_05_macro"/>
  </group>
  <group name="asteroid_nividium_s" resource="nividium" yield="100" yieldvariation="0.5">
    <select macro="env_ast_niv_s_01_macro"/>
    <select macro="env_ast_niv_s_02_macro"/>
    <select macro="env_ast_niv_s_03_macro"/>
    <select macro="env_ast_niv_s_04_macro"/>
    <select macro="env_ast_niv_s_05_macro"/>
  </group>
  <group name="asteroid_nividium_xs" resource="nividium" yield="10" yieldvariation="0.5">
    <select macro="env_ast_niv_xs_01_macro"/>
    <select macro="env_ast_niv_xs_02_macro"/>
    <select macro="env_ast_niv_xs_03_macro"/>
    <select macro="env_ast_niv_xs_04_macro"/>
    <select macro="env_ast_niv_xs_05_macro"/>
  </group>
  <group name="asteroid_ice_xl" resource="ice" yield="800" yieldvariation="0.5">
    <select macro="env_ast_ice_xl_01_macro"/>
  </group>
  <group name="asteroid_ice_l" resource="ice" yield="400" yieldvariation="0.5">
    <select macro="env_ast_ice_l_01_macro"/>
    <select macro="env_ast_ice_l_02_macro"/>
    <select macro="env_ast_ice_l_03_macro"/>
  </group>
  <group name="asteroid_ice_m" resource="ice" yield="200" yieldvariation="0.5">
    <select macro="env_ast_ice_m_01_macro"/>
    <select macro="env_ast_ice_m_02_macro"/>
    <select macro="env_ast_ice_m_03_macro"/>
    <select macro="env_ast_ice_m_04_macro"/>
    <select macro="env_ast_ice_m_05_macro"/>
    <select macro="env_ast_ice_m_06_macro"/>
  </group>
  <group name="asteroid_ice_s" resource="ice" yield="100" yieldvariation="0.5">
    <select macro="env_ast_ice_s_01_macro"/>
    <select macro="env_ast_ice_s_02_macro"/>
    <select macro="env_ast_ice_s_03_macro"/>
    <select macro="env_ast_ice_s_04_macro"/>
    <select macro="env_ast_ice_s_05_macro"/>
    <select macro="env_ast_ice_s_06_macro"/>
  </group>
  <group name="asteroid_ice_xs" resource="ice" yield="10" yieldvariation="0.5">
    <select macro="env_ast_ice_xs_01_macro"/>
    <select macro="env_ast_ice_xs_02_macro"/>
    <select macro="env_ast_ice_xs_03_macro"/>
    <select macro="env_ast_ice_xs_04_macro"/>
    <select macro="env_ast_ice_xs_05_macro"/>
    <select macro="env_ast_ice_xs_06_macro"/>
  </group>
  <group name="asteroid_ore_xxl_highyield" resource="ore" yield="8000" yieldvariation="0.5">
    <select macro="env_ast_ore_xxl_01_macro"/>
  </group>
  <group name="asteroid_ore_xl_highyield" resource="ore" yield="8000" yieldvariation="0.5">
    <select macro="env_ast_ore_xl_01_macro"/>
    <select macro="env_ast_ore_xl_02_macro"/>
  </group>
  <group name="asteroid_ore_l_highyield" resource="ore" yield="4000" yieldvariation="0.5">
    <select macro="env_ast_ore_l_01_macro"/>
    <select macro="env_ast_ore_l_02_macro"/>
    <select macro="env_ast_ore_l_03_macro"/>
    <select macro="env_ast_ore_l_04_macro"/>
    <select macro="env_ast_ore_l_05_macro"/>
  </group>
  <group name="asteroid_ore_m_highyield" resource="ore" yield="2000" yieldvariation="0.5">
    <select macro="env_ast_ore_m_01_macro"/>
    <select macro="env_ast_ore_m_02_macro"/>
    <select macro="env_ast_ore_m_03_macro"/>
    <select macro="env_ast_ore_m_04_macro"/>
    <select macro="env_ast_ore_m_05_macro"/>
    <select macro="env_ast_ore_m_06_macro"/>
  </group>
  <group name="asteroid_ore_s_highyield" resource="ore" yield="1000" yieldvariation="0.5">
    <select macro="env_ast_ore_s_01_macro"/>
    <select macro="env_ast_ore_s_02_macro"/>
    <select macro="env_ast_ore_s_03_macro"/>
    <select macro="env_ast_ore_s_04_macro"/>
    <select macro="env_ast_ore_s_05_macro"/>
  </group>
  <group name="asteroid_ore_xs_highyield" resource="ore" yield="100" yieldvariation="0.5">
    <select macro="env_ast_ore_xs_01_macro"/>
    <select macro="env_ast_ore_xs_02_macro"/>
    <select macro="env_ast_ore_xs_03_macro"/>
    <select macro="env_ast_ore_xs_04_macro"/>
    <select macro="env_ast_ore_xs_05_macro"/>
  </group>
  <group name="asteroid_silicon_xl_highyield" resource="silicon" yield="8000" yieldvariation="0.5">
    <select macro="env_ast_crystal_xl_01_macro"/>
  </group>
  <group name="asteroid_silicon_l_highyield" resource="silicon" yield="4000" yieldvariation="0.5">
    <select macro="env_ast_crystal_l_01_macro"/>
    <select macro="env_ast_crystal_l_02_macro"/>
    <select macro="env_ast_crystal_l_03_macro"/>
  </group>
  <group name="asteroid_silicon_m_highyield" resource="silicon" yield="2000" yieldvariation="0.5">
    <select macro="env_ast_crystal_m_01_macro"/>
    <select macro="env_ast_crystal_m_02_macro"/>
    <select macro="env_ast_crystal_m_03_macro"/>
    <select macro="env_ast_crystal_m_04_macro"/>
    <select macro="env_ast_crystal_m_05_macro"/>
